### ISSUE TITLE
Segfault on backslash during forward search

### ISSUE THREAD

**Issue by Palladinium** [arybczak/ncmpcpp#143]
Typing a backslash during a forward search segfaults with the stack trace below.

Also, typing a backslash during a backward search prints `Unexpected error: basic_string::_M_create` on the status line without crashing the program.

The `error.log` file is empty in both cases.

```
#0  0x00007ffff71c5adb in boost::re_detail_106000::basic_regex_parser<int, boost::icu_regex_traits>::parse_basic() () from /usr/lib/libboost_regex.so.1.60.0
#1  0x00007ffff71c48e2 in boost::re_detail_106000::basic_regex_parser<int, boost::icu_regex_traits>::parse(int const*, int const*, unsigned int) ()
   from /usr/lib/libboost_regex.so.1.60.0
#2  0x00007ffff71c4d6c in boost::basic_regex<int, boost::icu_regex_traits>::do_assign(int const*, int const*, unsigned int) () from /usr/lib/libboost_regex.so.1.60.0
#3  0x00000000004df98b in boost::basic_regex<int, boost::icu_regex_traits>::assign (this=0x7fffffffcfc0, p1=0xe77ac0, p2=0xe77ac4, f=3211265)
    at /usr/include/boost/regex/v4/basic_regex.hpp:381
#4  0x00000000004df812 in boost::basic_regex<int, boost::icu_regex_traits>::basic_regex<boost::u8_to_u32_iterator<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, int> > (this=0x7fffffffcfc0, arg_first=..., arg_last=..., f=3211265)
    at /usr/include/boost/regex/v4/basic_regex.hpp:403
#5  0x00000000004df6de in boost::re_detail_106000::do_make_u32regex<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (i=..., j=..., opt=3211265) at /usr/include/boost/regex/icu.hpp:254
#6  0x00000000004df630 in boost::make_u32regex<char, std::char_traits<char>, std::allocator<char> > (s=..., opt=3211265) at /usr/include/boost/regex/icu.hpp:378
#7  0x00000000004b9955 in Regex::make<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (s=..., flags=3211265)
    at ./regex_filter.h:50
#8  0x00000000005795b7 in Playlist::setSearchConstraint (this=0xb53e70, constraint=...) at playlist.cpp:159
#9  0x000000000061ba22 in Statusbar::Helpers::FindImmediately::operator() (this=0xe77a50, s=0xa0d560 "\\") at statusbar.cpp:230
#10 0x0000000000467ed2 in std::_Function_handler<bool (char const*), Statusbar::Helpers::FindImmediately>::_M_invoke(std::_Any_data const&, char const*&&) (
    __functor=..., __args=<unknown type in /home/patrick/build/ncmpcpp/src/ncmpcpp, CU 0x37db9, DIE 0xb47a0>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1725
#11 0x0000000000664f78 in std::function<bool (char const*)>::operator()(char const*) const (this=0xe6b188, __args=0xa0d560 "\\")
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:2136
#12 0x00000000006638fc in NC::Window::runPromptHook (this=0xe6b140, arg=0xa0d560 "\\", done=0x7fffffffd197) at window.cpp:1157
#13 0x000000000065fcd9 in (anonymous namespace)::rl::read_key () at window.cpp:70
#14 0x00007ffff4cb57ed in rl_read_key () from /usr/lib/libreadline.so.6
#15 0x00007ffff4c9f3f2 in readline_internal_char () from /usr/lib/libreadline.so.6
#16 0x00007ffff4c9fb65 in readline () from /usr/lib/libreadline.so.6
#17 0x0000000000663652 in NC::Window::prompt (this=0xe6b140, base=..., width=18446744073709551615, encrypted=false) at window.cpp:1113
#18 0x0000000000448b4b in (anonymous namespace)::findItem (direction=SearchDirection::Forward) at actions.cpp:2926
#19 0x00000000004488b8 in Actions::FindItemForward::run (this=0xa309c0) at actions.cpp:1976
#20 0x000000000044d7b3 in Actions::BaseAction::execute (this=0xa309c0) at ./actions.h:103
#21 0x000000000045aa1d in std::__invoke_impl<bool, bool (Actions::BaseAction::* const&)(), Actions::BaseAction* const&> (
    __f=@0x7fffffffd7b0: (bool (Actions::BaseAction::*)(Actions::BaseAction * const)) 0x44d780 <Actions::BaseAction::execute()>, __t=@0xa27950: 0xa309c0)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:235
#22 0x000000000045a992 in std::__invoke<bool (Actions::BaseAction::* const&)(), Actions::BaseAction* const&> (
    __fn=@0x7fffffffd7b0: (bool (Actions::BaseAction::*)(Actions::BaseAction * const)) 0x44d780 <Actions::BaseAction::execute()>, __args=@0xa27950: 0xa309c0)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#23 0x000000000045a900 in std::_Mem_fn_base<bool (Actions::BaseAction::*)(), true>::operator()<Actions::BaseAction* const&> (this=0x7fffffffd7b0, 
    __args=@0xa27950: 0xa309c0) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#24 0x000000000045a873 in std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)>::__call<bool, Actions::BaseAction* const&, 0ul>(std::tuple<Actions::BaseAction* const&>&&, std::_Index_tuple<0ul>) (this=0x7fffffffd7b0, __args=<unknown type in /home/patrick/build/ncmpcpp/src/ncmpcpp, CU 0x37db9, DIE 0xae30b>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:942
#25 0x000000000045a7fd in std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)>::operator()<Actions::BaseAction* const&, bool>(Actions::BaseAction* const&) (this=0x7fffffffd7b0, __args=@0xa27950: 0xa309c0) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1000
#26 0x000000000045a790 in __gnu_cxx::__ops::_Iter_negate<std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> >::operator()<__gnu_cxx::__norma---Type <return> to continue, or q <return> to quit---
l_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > > >(__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >) (this=0x7fffffffd7b0, __it=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/predefined_ops.h:296
#27 0x000000000045a661 in std::__find_if<__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__ops::_Iter_negate<std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> > >(__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__ops::_Iter_negate<std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> >, std::random_access_iterator_tag) (__first=..., __last=..., __pred=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:148
#28 0x000000000045a3da in std::__find_if_not<__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> > >(__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> >) (
    __first=..., __last=..., __pred=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:171
#29 0x000000000045a31e in std::find_if_not<__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> >(__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)>) (__first=..., __last=..., __pred=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:566
#30 0x000000000045a135 in std::all_of<__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)> >(__gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, __gnu_cxx::__normal_iterator<Actions::BaseAction* const*, std::vector<Actions::BaseAction*, std::allocator<Actions::BaseAction*> > >, std::_Bind<std::_Mem_fn<bool (Actions::BaseAction::*)()> (std::_Placeholder<1>)>) (__first=..., __last=..., __pred=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:509
#31 0x000000000044ee82 in Binding::execute (this=0xa2e5e8) at ./bindings.h:47
#32 0x0000000000577fea in std::__invoke_impl<bool, bool (Binding::* const&)() const, Binding&> (
    __f=@0x7fffffffdbe0: (bool (Binding::*)(const Binding * const)) 0x44edf0 <Binding::execute() const>, __t=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:226
#33 0x0000000000577f62 in std::__invoke<bool (Binding::* const&)() const, Binding&> (
    __fn=@0x7fffffffdbe0: (bool (Binding::*)(const Binding * const)) 0x44edf0 <Binding::execute() const>, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:259
#34 0x0000000000577ef0 in std::_Mem_fn_base<bool (Binding::*)() const, true>::operator()<Binding&> (this=0x7fffffffdbe0, __args=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:613
#35 0x0000000000577e63 in std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)>::__call<bool, Binding&, 0ul>(std::tuple<Binding&>&&, std::_Index_tuple<0ul>) (this=0x7fffffffdbe0, __args=<unknown type in /home/patrick/build/ncmpcpp/src/ncmpcpp, CU 0x35972e, DIE 0x37746c>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:942
#36 0x0000000000577ded in std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)>::operator()<Binding&, bool>(Binding&) (this=0x7fffffffdbe0, 
    __args=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/functional:1000
#37 0x0000000000577d80 in __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> >::operator()<__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > > >(__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >) (
    this=0x7fffffffdbe0, __it=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/predefined_ops.h:234
#38 0x0000000000577ca1 in std::__find_if<__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> > >(__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> >, std::random_access_iterator_tag) (__first=..., __last=..., __pred=...)
---Type <return> to continue, or q <return> to quit---
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:148
#39 0x0000000000577a21 in std::__find_if<__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> > >(__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__ops::_Iter_pred<std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> >) (__first=..., __last=..., __pred=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:161
#40 0x000000000057799e in std::find_if<__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> >(__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)>) (__first=..., __last=..., __pred=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:3824
#41 0x00000000005778e5 in std::none_of<__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> >(__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)>) (__first=..., __last=..., __pred=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:526
#42 0x00000000005764b5 in std::any_of<__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)> >(__gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, __gnu_cxx::__normal_iterator<Binding*, std::vector<Binding, std::allocator<Binding> > >, std::_Bind<std::_Mem_fn<bool (Binding::*)() const> (std::_Placeholder<1>)>) (__first=..., __last=..., __pred=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/stl_algo.h:544
#43 0x0000000000575f4e in main (argc=1, argv=0x7fffffffe1f8) at ncmpcpp.cpp:221
```

**Comment by arybczak** [comment]
See https://bugs.musicpd.org/view.php?id=4532.
