### ISSUE TITLE
Segfault with quiet option

### ISSUE THREAD

**Issue by jfrankenau** [arybczak/ncmpcpp#245]
When starting ncmpcpp with the `-q`/`--quiet` option introduced with #200, ncmpcpp fails with

    [1]    24609 segmentation fault (core dumped)  ncmpcpp -q

I am using Arch Linux with [ncmpcpp 0.8-1](https://www.archlinux.org/packages/community/x86_64/ncmpcpp/) which runs fine without the quiet option.

Stack trace
```
Stack trace of thread 24609:
#0  0x00007f194cd46ef1 _ZNSt15basic_streambufIcSt11char_traitsIcEE5sputnEPKcl (libstdc++.so.6)
#1  0x0000000000567c2e n/a (ncmpcpp)
#2  0x000000000056ee6d n/a (ncmpcpp)
#3  0x0000000000532240 n/a (ncmpcpp)
#4  0x0000000000429cc9 n/a (ncmpcpp)
#5  0x00007f194c3844ca __libc_start_main (libc.so.6)
#6  0x000000000042b46a n/a (ncmpcpp)
```

GDB backtrace
```
Core was generated by `ncmpcpp -q'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f194cd46ef1 in std::basic_streambuf<char, std::char_traits<char> >::sputn (__n=27, __s=0x611e7e "Reading configuration from ", this=0x7fffe5d8ffe8)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:451
(gdb) bt
#0  0x00007f194cd46ef1 in std::basic_streambuf<char, std::char_traits<char> >::sputn (__n=27, __s=0x611e7e "Reading configuration from ", this=0x7fffe5d8ffe8)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/streambuf:451
#1  std::__ostream_write<char, std::char_traits<char> > (__n=27, __s=0x611e7e "Reading configuration from ", __out=...)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:50
#2  std::__ostream_insert<char, std::char_traits<char> > (__out=..., __s=0x611e7e "Reading configuration from ", __n=27)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/ostream_insert.h:101
#3  0x0000000000567c2e in ?? ()
#4  0x000000000056ee6d in ?? ()
#5  0x0000000000532240 in ?? ()
#6  0x0000000000429cc9 in ?? ()
#7  0x00007f194c3844ca in __libc_start_main () from /usr/lib/libc.so.6
#8  0x000000000042b46a in ?? ()
```

**Comment by hghwng** [comment]
I can reproduce the crash with 0.8 dev

**Comment by arybczak** [comment]
Please test if db28618929b9ec11e831d5a44437757f6195497d fixes the problem.

**Comment by jfrankenau** [comment]
@arybczak, https://github.com/arybczak/ncmpcpp/commit/db28618929b9ec11e831d5a44437757f6195497d works fine for me. Thank you!
